$csv = 
@"
OBJECTID,HierarchyKey,GeoMaterial,IndentedName,Definition
1,01,Sedimentary material,Sedimentary material,"An aggregation of particles deposited by gravity, air, water, or ice, or as accumulated by other natural agents operating at Earth's surface such as chemical precipitation or secretion by organisms.  May include unconsolidated material (sediment) and (or) sedimentary rock.  Does not include sedimentary material directly deposited as a result of volcanic activity."
2,01.01,Sediment,--Sediment,"Unconsolidated material (sediment) composed of particles deposited by gravity, air, water, or ice, or as accumulated by other natural agents operating at Earth's surface such as chemical precipitation or secretion by organisms.  Does not include sedimentary material directly deposited as a result of volcanic activity."
3,01.01.01,Clastic sediment,----Clastic sediment,"Sediment formed by the weathering and erosion of preexisting rocks or minerals; the eroded particles or ""clasts"" are transported and deposited by gravity, air, water, or ice."
4,01.01.01.01,Sand and gravel of unspecified origin,------Sand and gravel of unspecified origin,"A sediment composed mostly of sand and (or) gravel, formed by the weathering and erosion of preexisting rocks or minerals; the eroded particles or ""clasts"" are transported and deposited by gravity, air, water, or ice."
5,01.01.01.02,Silt and clay of unspecified origin,------Silt and clay of unspecified origin,"A sediment composed mostly of silt and (or) clay, formed by the weathering and erosion of preexisting rocks or minerals; the eroded particles or ""clasts"" are transported and deposited by gravity, air, water, or ice."
6,01.01.01.03,Alluvial sediment,------Alluvial sediment,"Unconsolidated material deposited by a stream or other body of running water, as a sorted or semi-sorted sediment in the bed of the stream or on its floodplain or delta, or as a cone or fan at the base of a mountain slope.  Grain size varies from clay to gravel."
7,01.01.01.03.01,"Alluvial sediment, mostly coarse-grained","--------Alluvial sediment, mostly coarse-grained","Unconsolidated material deposited by a stream or other body of running water, as a sorted or semi-sorted sediment in the bed of the stream or on its floodplain or delta, or as a cone or fan at the base of a mountain slope.  This sediment is mostly sand, gravel, and coarser material, but may contain some silt and clay."
8,01.01.01.03.02,"Alluvial sediment, mostly fine-grained","--------Alluvial sediment, mostly fine-grained","Unconsolidated material deposited by a stream or other body of running water, as a sorted or semi-sorted sediment in the bed of the stream or on its floodplain or delta, or as a cone or fan at the base of a mountain slope.  This sediment is mostly silt and clay, but may contain some sand and gravel."
9,01.01.01.04,Glacial till,------Glacial till,"Mostly unsorted and unstratified material, generally unconsolidated, deposited directly by and underneath or adjacent to a glacier without subsequent reworking by meltwater, and consisting of a heterogeneous mixture of clay, silt, sand, gravel, and boulders ranging widely in size and shape."
10,01.01.01.04.01,"Glacial till, mostly sandy","--------Glacial till, mostly sandy","Mostly unsorted and unstratified material, generally unconsolidated, deposited directly by and underneath or adjacent to a glacier without subsequent reworking by meltwater, and consisting of clay, silt, sand, gravel, and boulders ranging widely in size and shape.  Relatively sandy in texture."
11,01.01.01.04.02,"Glacial till, mostly silty","--------Glacial till, mostly silty","Mostly unsorted and unstratified material, generally unconsolidated, deposited directly by and underneath or adjacent to a glacier without subsequent reworking by meltwater, and consisting of a heterogeneous mixture of clay, silt, sand, gravel, and boulders ranging widely in size and shape.  Relatively loamy (silty) in texture."
12,01.01.01.04.03,"Glacial till, mostly clayey","--------Glacial till, mostly clayey","Mostly unsorted and unstratified material, generally unconsolidated, deposited directly by and underneath or adjacent to a glacier without subsequent reworking by meltwater, and consisting of a heterogeneous mixture of clay, silt, sand, gravel, and boulders ranging widely in size and shape.  Relatively clayey in texture."
13,01.01.01.05,Ice-contact and ice-marginal sediment,------Ice-contact and ice-marginal sediment,"Mostly sand, silt, and gravel-sized particles or ""clasts"" derived from rock or preexisting sediment eroded and transported by glaciers.  As the glacier melted, this material was deposited by running water essentially in contact with glacial ice, or was transported and deposited by glacially fed streams.  Includes sediment deposited into water bodies adjacent to the glacier."
14,01.01.01.05.01,"Ice-contact and ice-marginal sediment, mostly coarse-grained","--------Ice-contact and ice-marginal sediment, mostly coarse-grained","Mostly sand and gravel-sized particles or ""clasts,"" with lesser silt and clay, derived from rock or preexisting sediment eroded and transported by glaciers.  As the glacier melted, this material was deposited by running water essentially in contact with glacial ice, or was transported and deposited by glacially fed streams.  Includes sediment deposited into water bodies adjacent to the glacier."
15,01.01.01.05.02,"Ice-contact and ice-marginal sediment, mostly fine-grained","--------Ice-contact and ice-marginal sediment, mostly fine-grained","Mostly silt and clay-sized particles or ""clasts,"" with lesser sand and gravel, derived from rock or preexisting sediment eroded and transported by glaciers.  As the glacier melted, this material was deposited by running water essentially in contact with glacial ice, or was transported and deposited by glacially fed streams.  Includes sediment deposited into water bodies adjacent to the glacer."
16,01.01.01.06,Eolian sediment,------Eolian sediment,Silt- and sand-sized sediment deposited by wind.
17,01.01.01.06.01,Dune sand,--------Dune sand,Mostly sand-sized sediment deposited by wind.  Typically characterized by various dune landforms.
18,01.01.01.06.02,Loess,--------Loess,"Silty material deposited by winds, commonly near a glacial margin."
19,01.01.01.07,Lacustrine sediment,------Lacustrine sediment,"Mostly well sorted and well bedded material ranging in grain size from clay to gravel, deposited in perennial to intermittent lakes.  Much of the sediment is derived from material eroded and transported by streams.  Includes deposits of lake-marginal beaches and deltas."
20,01.01.01.07.01,"Lacustrine sediment, mostly coarse-grained","--------Lacustrine sediment, mostly coarse-grained","Mostly well-sorted and well-bedded material, generally sand- and gravel-sized with lesser silt and clay, deposited in perennial to intermittent lakes.  Much of the sediment is derived from material eroded and transported by streams. Mostly deposits of lake-marginal beaches and deltas."
21,01.01.01.07.02,"Lacustrine sediment, mostly fine-grained","--------Lacustrine sediment, mostly fine-grained","Mostly well-sorted and well-bedded material, generally silt- and clay-sized with lesser sand, deposited in perennial to intermittent lakes."
22,01.01.01.08,Playa sediment,------Playa sediment,"Fine-grained clastic sediment and evaporitic salts deposited in ephemeral lakes in the centers of undrained basins.  Includes material deposited in playas, mudflats, salt flats, and adjacent saline marshes.  Generally interbedded with eolian sand and with lacustrine sediment deposited during wetter climatic periods; commonly intertongues upslope with sediment deposited by alluvial fans."
23,01.01.01.09,Coastal zone sediment  ,------Coastal zone sediment  ,"Mud, sand, and lesser gravel deposited in beach, barrier island, nearshore marine deltaic, or in various low-energy shoreline (mud flat, tidal flat, sabka, algal flat) settings."
24,01.01.01.09.01,"Coastal zone sediment, mostly coarse-grained","--------Coastal zone sediment, mostly coarse-grained","Mostly sand, silt, and gravel deposited on beaches and dunes, and in shallow marine and related alluvial environments."
25,01.01.01.09.02,"Coastal zone sediment, mostly fine-grained","--------Coastal zone sediment, mostly fine-grained","Mostly clay and silt deposited in lagoons, tidal flats, backbarriers, and coastal marshes."
26,01.01.01.10,Marine sediment,------Marine sediment,"Mud and sand deposited in various marine settings.  Sediment may originate from erosion of rocks and sediments on land, or from marine organisms (of carbonate or siliceous composition)."
27,01.01.01.10.01,"Marine sediment, mostly coarse-grained","--------Marine sediment, mostly coarse-grained","Mud and sand derived from erosion of rocks and sediment on land, transport by streams, and deposition in marine deltas and basins.  Sediment is mostly siliceous in composition."
28,01.01.01.10.02,"Marine sediment, mostly fine-grained ","--------Marine sediment, mostly fine-grained ","Mostly clay- and silt-sized sediment deposited in relatively deep, quiet water, far removed from areas where coarser-grained clastic sediments are washed into the marine environment.   Includes sediment derived from marine organisms."
29,01.01.01.11,Mass movement sediment,------Mass movement sediment,"Sediment formed by downslope transport of particles or ""clasts"" produced by weathering and breakdown of the underlying rock, sediment, and (or) soil.  Composed of poorly sorted and poorly stratified material ranging in size from clay to boulders.  Includes colluvium, landslide deposits, talus, and rock avalanche deposits."
30,01.01.01.11.01,Colluvium and other widespread mass-movement sediment,--------Colluvium and other widespread mass-movement sediment,"Sediment formed by relatively widespread and slow downslope transport of particles or ""clasts"" produced by weathering and breakdown of the underlying rock, sediment, and (or) soil.  Composed of poorly sorted and poorly stratified material ranging in size from clay to boulders."
31,01.01.01.11.02,"Debris flows, landslides, and other localized mass-movement sediment","--------Debris flows, landslides, and other localized mass-movement sediment","Sediment formed by relatively localized downslope transport of particles or ""clasts"" produced by weathering and breakdown of the underlying rock, sediment, and (or) soil.  Composed of poorly sorted and poorly stratified material ranging in size from clay to boulders.  The speed of downslope transport ranges from rapid to imperceptible."
32,01.01.02,Residual material,----Residual material,Unconsolidated material developed in place by weathering of the underlying rock or sediment.  Usually forms a relatively thin surface layer that conceals the unweathered or partly altered source material. The material from which soils are formed.
33,01.01.03,Carbonate sediment,----Carbonate sediment,"Sediment formed by the biotic or abiotic precipitation from aqueous solution of carbonates of calcium, magnesium, or iron; e.g., limestone, dolomite."
34,01.01.04,Peat and muck,----Peat and muck,"Unconsolidated material principally composed of plant remains, with lesser amounts of fine-grained clastic sediment.  Deposited in a water-saturated environment such as a swamp, marsh, or bog.  With lithification such material becomes coal."
35,01.02,Sedimentary rock,--Sedimentary rock,"Consolidated material (rock) composed of particles transported and deposited by gravity, air, water, or ice, or accumulated by other natural agents operating at Earth's surface such as chemical precipitation or secretion by organisms.  Does not here include sedimentary material directly deposited as a result of volcanic activity."
36,01.02.01,Clastic sedimentary rock,----Clastic sedimentary rock,"Sedimentary rock composed dominantly of particles or ""clasts"" derived by erosion, weathering, or mass-wasting of preexisting rock, and deposited by gravity, air, water, or ice."
37,01.02.01.01,Conglomerate,------Conglomerate,"Sedimentary rock composed dominantly of particles or ""clasts"" derived by erosion and weathering of preexisting rock, and containing more than 30 percent gravel-sized particles."
38,01.02.01.02,Sandstone,------Sandstone,"Sedimentary rock composed dominantly of particles or ""clasts"" derived by erosion and weathering of preexisting rock, consisting mostly of sand-sized particles, with or without a fine-grained matrix of silt or clay."
39,01.02.01.03,Mostly sandstone,------Mostly sandstone,"Mostly sandstone, interbedded with other sedimentary rocks which locally may include conglomerate and finer grained clastics (mudrock), carbonates, and (or) coal."
40,01.02.01.04,Sandstone and mudstone,------Sandstone and mudstone,Sandstone and mudstone (which includes shale and siltstone) in approximately equal (or unspecified) proportion. 
41,01.02.01.05,Mudstone,------Mudstone,"Sedimentary rock composed dominantly of particles or ""clasts"" derived by erosion and weathering of preexisting rock, consisting mostly of mud (silt- and clay-sized particles).  Includes shale and siltstone."
42,01.02.01.06,Mostly mudstone,------Mostly mudstone,"Mostly mudstone, interbedded with other sedimentary rocks which locally may include coarser grained clastics (sandstone, conglomerate), carbonates, and (or) coal."
43,01.02.02,Carbonate rock,----Carbonate rock,"Sedimentary rock consisting chiefly of carbonate minerals, such as limestone or dolomite. "
44,01.02.02.01,Limestone,------Limestone,Carbonate sedimentary rock consisting chiefly of the mineral calcite.
45,01.02.02.02,Dolomite,------Dolomite,"Carbonate sedimentary rock consisting chiefly of the mineral dolomite.  Although ""dolostone"" is the proper analog to limestone, it has not often been applied to dolomitic units; historically, the literature used ""dolomite."
46,01.02.03,Mostly carbonate rock,----Mostly carbonate rock,Mostly carbonate rock interbedded with other sedimentary rock types.
47,01.02.04,Chert,----Chert,Sedimentary rock composed chiefly of microcrystalline or cryptocrystalline quartz.
48,01.02.05,Evaporitic rock,----Evaporitic rock,"Sedimentary rock composed primarily of minerals produced by evaporation of a saline solution.  Examples include gypsum, anhydrite, other diverse sulfates, halite (rock salt), primary dolomite, and rocks composed of various nitrates and borates."
49,01.02.06,Iron-rich sedimentary rock,----Iron-rich sedimentary rock,"Sedimentary rock in which at least half (by volume) of the observed minerals are iron-bearing (hematite, magnetite, limonite-group, siderite, iron sulfides)."
50,01.02.07,Coal and lignite,----Coal and lignite,"Organic-rich sedimentary rock formed from the compaction and alteration of plant remains.  Coal is a consolidated, harder, black rock. Lignite is a semiconsolidated brown to black, earthy material which may contain large particles of recognizable plant parts and tends to crack upon drying."
51,02,Sedimentary and extrusive igneous material,Sedimentary and extrusive igneous material,Either (1) sedimentary rock and (or) unconsolidated material (sediment) and extrusive igneous material (volcanic rock and (or) sediment) or (2) volcanic rock and (or) sediment and such material after erosion and redeposition.
52,03,Igneous rock,Igneous rock,Rock and fragmental material that solidified from molten or partly molten material (magma). 
53,03.01,Extrusive igneous material,--Extrusive igneous material,"Molten material that was erupted onto the surface of the Earth, fusing into rock or remaining as unconsolidated particles.  Includes pyroclastic flows, air-fall tephra, lava flows, and volcanic mass flows."
54,03.01.01,Volcaniclastic (fragmental) material,----Volcaniclastic (fragmental) material,"Rock and unconsolidated material consisting of particles or ""clasts"" that were formed by volcanic explosion or aerial expulsion from a volcanic vent."
55,03.01.01.01,Pyroclastic flows,------Pyroclastic flows,"Hot ash, pumice, and rock fragments erupted from a volcano or caldera.  This material moves downslope commonly in chaotic flows.  Once deposited, the hot fragments may compact under their own weight and and weld together."
56,03.01.01.01.01,Felsic-composition pyroclastic flows,--------Felsic-composition pyroclastic flows,"Hot ash, pumice, and rock fragments erupted from a volcano or caldera.  This material moves downslope commonly in chaotic flows.  Once deposited, hot fragments may compact under their own weight and and weld together.  Composed of light-colored rocks (e.g., rhyolite, dacite, trachyte, latite) which, because of their high-silica content and resulting high viscosity, tend to erupt explosively."
57,03.01.01.01.02,Intermediate-composition pyroclastic flows,--------Intermediate-composition pyroclastic flows,"Hot ash, pumice, and rock fragments erupted from a volcano.  This material moves downslope commonly in chaotic flows.  Once deposited, hot fragments may compact under their own weight and and weld together.  Composed of rocks (e.g., andesite) intermediate in color and mineral composition between felsic and mafic rocks.  Andesite magma commonly erupts from stratovolcanoes as thick lava flows but also can generate strong explosive eruptions to form pyroclastic flows."
58,03.01.01.01.03,Mafic-composition pyroclastic flows,--------Mafic-composition pyroclastic flows,"Hot ash, pumice, and rock fragments erupted from a volcano.  This material moves downslope commonly in chaotic flows.  Once deposited, hot fragments may compact under their own weight and and weld together.  Composed of dark-colored rocks (e.g., basalt) which, because of their low silica content and resulting low viscosity, tend to erupt gently as lava flows rather than more forcefully as pyroclastic flows."
59,03.01.01.02,Air-fall tephra,------Air-fall tephra,"Fragments of volcanic rock and lava, of various sizes, are known as ""tephra.""  This material is carried into the air by explosions and by hot gases in eruption columns or lava fountains.  As tephra falls to the ground with increasing distance from a volcano, the average size of the individual rock particles and the thickness of the resulting deposit decrease.  Fine tephra deposited at some distance from a volcano is known as volcanic ash."
60,03.01.01.02.01,Felsic-composition air-fall tephra,--------Felsic-composition air-fall tephra,"Fragments of volcanic rock and lava, of various sizes, are known as ""tephra.""  This material is carried into the air by explosions and by hot gases in eruption columns or lava fountains.  As tephra falls to the ground with increasing distance from a volcano, the average size of the individual rock particles and the thickness of the resulting deposit decrease.  Composed of light-colored rocks (e.g., rhyolite, dacite, trachyte, latite) which, because of their high-silica content and resulting high viscosity, tend to erupt explosively, readily forming pumice and volcanic ash."
61,03.01.01.02.02,Intermediate-composition air-fall tephra,--------Intermediate-composition air-fall tephra,"Fragments of volcanic rock and lava, of various sizes, are known as ""tephra.""  This material is carried into the air by explosions and by hot gases in eruption columns or lava fountains.  As tephra falls to the ground with increasing distance from a volcano, the average size of the individual rock particles and the thickness of the resulting deposit decrease.  Composed of rocks (e.g., andesite) intermediate in color and mineral composition between felsic and mafic rocks.  Andesite magma commonly erupts from stratovolcanoes as thick lava flows but also can generate strong explosive eruptions, readily forming pumice and volcanic ash."
62,03.01.01.02.03,Mafic-composition air-fall tephra,--------Mafic-composition air-fall tephra,"Fragments of volcanic rock and lava, of various sizes, are known as ""tephra.""  This material is carried into the air by explosions and by hot gases in eruption columns or lava fountains.  As tephra falls to the ground with increasing distance from a volcano, the average size of the individual rock particles and the thickness of the resulting deposit decrease.  Composed of dark-colored rocks (e.g., basalt) which, because of their low silica content and resulting low viscosity, tend to erupt gently as lava flows rather than more forcefully, and so these deposits are uncommon."
63,03.01.02,Lava flows,----Lava flows,"Lateral, surficial outpourings of molten lava from a vent or a fissure, and the solidified bodies of rock that form when they cool.  Composed generally of fine-grained, dark-colored rocks (e.g., basalt), which tend to form extensive sheets with generally low relief except in the vent areas where cinder cones or shield volcanoes may form.  Includes basaltic shield volcanoes, which may become very large (e.g., Hawaii)."
64,03.01.02.01,Felsic-composition lava flows,------Felsic-composition lava flows,"Lateral, surficial outpourings of molten lava from a vent or a fissure, and the solidified bodies of rock that form when they cool.  Composed of fine-grained, light-colored rocks which, because of their high-silica content and resulting high viscosity, tend to erupt explosively, and so these deposits are uncommon.  Includes rhyolitic, dacitic, trachytic, and latitic rock."
65,03.01.02.02,Intermediate-composition lava flows,------Intermediate-composition lava flows,"Lateral, surficial outpourings of molten lava from a vent or a fissure, and the solidified bodies of rock that forms when they cool.  Composed of fine-grained rocks intermediate in color and mineral composition between felsic and mafic rocks, and commonly erupts from stratovolcanoes as thick lava flows.  Includes andesitic rock."
66,03.01.02.03,Mafic-composition lava flows,------Mafic-composition lava flows,"Lateral, surficial outpourings of molten lava from a vent or a fissure, and the solidified bodies of rock that form when they cool.  Composed of fine-grained, dark-colored rocks, and tends to form extensive sheets with generally low relief.  Includes basaltic shield volcanoes, which may become very large (e.g., Hawaii).  Includes basaltic rock."
67,03.01.03,Volcanic mass flow,----Volcanic mass flow,"Deposit formed by mass movement, i.e., debris avalanches, debris flows, or lahars.  In many cases these are triggered by volcanic eruption.  Debris avalanches occurring on volcanoes clearly without an eruptive trigger may be classified as sedimentary mass movement."
68,03.02,Intrusive igneous rock,--Intrusive igneous rock,"Rock that solidified from molten or partly molten material magma), forming below the Earth's surface."
69,03.02.01,Coarse-grained intrusive igneous rock,----Coarse-grained intrusive igneous rock,"Rock that solidified from molten or partly molten material (magma).  It formed at some depth beneath the Earth's surface, thereby cooling slowly enough for mineral crystals to grow to a size large enough to be visible to the naked eye."
70,03.02.01.02,"Coarse-grained, felsic-composition intrusive igneous rock","------Coarse-grained, felsic-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at some depth beneath the Earth's surface, thereby cooling slowly enough for mineral crystals to grow to a size large enough to be visible to the naked eye.  Composed mostly of light-colored minerals, e.g., feldspar, quartz.  Includes granitic, syenitic, and monzonitic rock."
71,03.02.01.03,"Coarse-grained, intermediate-composition intrusive igneous rock","------Coarse-grained, intermediate-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at some depth beneath the Earth's surface, thereby cooling slowly enough for mineral crystals to grow to a size large enough to be visible to the naked eye.  Intermediate in color and mineral composition between felsic and mafic igneous rock.  Includes dioritic rock."
72,03.02.01.04,"Coarse-grained, mafic-composition intrusive igneous rock","------Coarse-grained, mafic-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at some depth beneath the Earth's surface, thereby cooling slowly enough for mineral crystals to grow to a size large enough to be visible to the naked eye.  Composed mostly of feldspar and dark-colored minerals.  Includes gabbroic rock."
73,03.02.01.05,Ultramafic intrusive igneous rock,------Ultramafic intrusive igneous rock,"Rock that solidified from molten or partly molten material (magma).  It formed at some depth beneath the Earth's surface, thereby cooling slowly enough for mineral crystals to grow to a size large enough to be visible to the naked eye.  Composed almost entirely of mafic minerals, e.g., hypersthene, augite, olivine."
74,03.02.02,Fine-grained intrusive igneous rock,----Fine-grained intrusive igneous rock,"Rock that solidified from molten or partly molten material (magma).  It formed at shallow depths beneath the Earth's surface, thereby cooling quickly.  These rocks generally are fine-grained, but may contain large mineral crystals (phenocrysts), and they mostly occur as tabular dikes or sills."
75,03.02.02.01,"Fine-grained, felsic-composition intrusive igneous rock","------Fine-grained, felsic-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at shallow depths beneath the Earth's surface, thereby cooling quickly.  These rocks generally are fine-grained, but may contain large mineral crystals (phenocrysts), and they occur mostly as tabular dikes or sills.  Composed mostly of light-colored minerals.  Includes rhyolitic, dacitic, trachytic, and latitic rock."
76,03.02.02.02,"Fine-grained, intermediate-composition intrusive igneous rock","------Fine-grained, intermediate-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at shallow depths beneath the Earth's surface, thereby cooling quickly.  These rocks generally are fine-grained, but may contain large mineral crystals (phenocrysts), and they occur mostly as tabular dikes or sills.  Intermediate in color and mineral composition between felsic and mafic igneous rock. Includes andesitic rock."
77,03.02.02.03,"Fine-grained, mafic-composition intrusive igneous rock","------Fine-grained, mafic-composition intrusive igneous rock","Rock that solidified from molten or partly molten material (magma).  It formed at shallow depths beneath the Earth's surface, thereby cooling quickly.  These rocks generally are fine-grained, but may contain large mineral crystals (phenocrysts), and they occur mostly as tabular dikes or sills.  Composed mostly of dark-colored minerals.  Includes basaltic rock."
78,03.02.03,Exotic-composition intrusive igneous rock,----Exotic-composition intrusive igneous rock,"Rock that solidified from molten or partly molten material (magma), forming below the Earth's surface and having exotic mineralogical, textural, or field setting characteristics.  These rocks typically are dark colored with abundant phenocrysts. Includes kimberlite, lamprophyre, lamproite, and foiditic rocks."
79,04,Igneous and metamorphic rock,Igneous and metamorphic rock,Consists of coarse-grained intrusive igneous rocks and generally medium to high grade metamorphic rocks.
80,05,Metamorphic rock,Metamorphic rock,"A rock derived from preexisting rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust."
81,05.01,Regional metamorphic rock of unspecified origin,--Regional metamorphic rock of unspecified origin,"A rock derived from preexisting rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked regional changes in temperature, pressure, deformation, and (or) chemical environment, generally at depth in the Earth's crust.  Origin of the preexisting rock is mixed (e.g., igneous and sedimentary) or is not known. "
82,05.01.01,Lower-grade metamorphic rock of unspecified origin,----Lower-grade metamorphic rock of unspecified origin,"A rock derived from preexisting rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to relatively mild regional changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Origin of the preexisting rock is mixed (e.g., igneous and sedimentary) or is not known.  Includes slate and phyllite."
83,05.01.02,Higher-grade regional metamorphic rock of unspecified origin,----Higher-grade regional metamorphic rock of unspecified origin,"A rock derived from preexisting rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to relatively intense regional changes in temperature, pressure, deformation, and (or) chemical environment, generally at depth in the Earth's crust.  Origin of the preexisting rock is mixed (e.g., igneous and sedimentary) or is not known.  Includes amphibolite, granulite, schist, and gneiss."
84,05.01.03,Contact-metamorphic rock,----Contact-metamorphic rock,"Rock that originated by local processes of thermal metamorphism, genetically related to the intrusion and extrusion of magmas and taking place in rocks at or near their contact with a body of igneous rock.  Metamorphic changes are effected by the heat and fluids emanating from the magma and by some deformation because of emplacement of the igneous mass."
85,05.01.04,Deformation-related metamorphic rock,----Deformation-related metamorphic rock,"A rock derived from preexisting rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to strong deformation, commonly in association with marked changes in temperature, pressure, and (or) chemical environment.  Generally forms in narrow, planar zones of local deformation (e.g., along faults) and characterized by foliation or alignment of mineral grains.  Includes mylonite and cataclasite."
86,05.02,Metasedimentary rock,--Metasedimentary rock,"A rock derived from preexisting sedimentary rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and (or) chemical environment, generally at depth in the Earth's crust."
87,05.02.01,Slate and phyllite of sedimentary rock origin,----Slate and phyllite of sedimentary rock origin,"A fine-grained rock derived from preexisting sedimentary rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and (or) chemical environment, generally at depth in the Earth's crust.  Includes phyllite and slate, which is a compact, fine-grained rock that possesses strong cleavage and hence can be split into slabs and thin plates.  Mostly formed from fine-grained material such as mudstone."
88,05.02.02,Schist and gneiss of sedimentary rock origin,----Schist and gneiss of sedimentary rock origin,"A foliated rock derived from preexisting sedimentary rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and (or) chemical environment, generally at depth in the Earth's crust.  Includes schist (characterized by such strong foliation or alignment of minerals that it readily splits into flakes or slabs) and gneiss (characterized by alternating, irregular bands of different mineral composition).  Mostly formed from fine-grained material such as mudstone."
89,05.02.03,Meta-carbonate rock,----Meta-carbonate rock,"A rock derived from preexisting carbonate sedimentary rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Characterized by recrystallization of the carbonate minerals in the source rock.  Includes marble, for which the preexisting rock was dominantly limestone or other rock composed of the mineral calcite, and dolomitic marble, meta-dolostone, or meta-dolomite, for which the preexisting rock contained appreciable magnesium."
90,05.02.04,Quartzite,----Quartzite,"A rock derived from preexisting (commonly sandstone) sedimentary rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, shear stress, and (or) chemical environment, generally at depth in the Earth's crust.  Characterized by recrystallization of quartz in the source rock."
91,05.03,Metaigneous rock,--Metaigneous rock,"A rock derived from preexisting igneous rocks by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, shear stress, and (or) chemical environment, generally at depth in the Earth's crust.  "
92,05.03.01,Meta-ultramafic rock,----Meta-ultramafic rock,"A rock derived from preexisting ultramafic rocks and altered by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Composed mostly of Mg-bearing minerals, e.g., serpentine, talc, and magnesite."
93,05.03.02,Meta-mafic rock,----Meta-mafic rock,"A rock derived from preexisting mafic rocks and altered by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Composed mostly of Fe- and Mg-bearing dark-colored and green minerals.  Includes greenstone, amphibolite, and metagabbro."
94,05.03.03,Meta-felsic and -intermediate rock,----Meta-felsic and -intermediate rock,"A rock derived from preexisting felsic and intermediate rocks and altered by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Composed mostly of light-colored minerals and relatively enriched in silica.  Includes metagranite, metadiorite, and meta-andesite."
95,05.03.04,Meta-volcaniclastic rock,----Meta-volcaniclastic rock,"A rock derived from preexisting volcaniclastic rocks and altered by mineralogical, chemical, or structural changes, essentially in the solid state, in response to marked changes in temperature, pressure, deformation, and chemical environment, generally at depth in the Earth's crust.  Composed of deformed but recognizable particles or ""clasts"" of volcanic explosive material."
96,06,Other materials,Other materials,--please select a subdivision--
97,06.01,Rock and sediment,--Rock and sediment,"Various rocks and sediment, not differentiated."
98,06.02,Rock,--Rock,"Various rock types, not differentiated."
99,06.03,"""Made"" or human-engineered land","--""Made"" or human-engineered land","Modern, unconsolidated material known to have human-related origin."
100,06.04,Water or ice,--Water or ice,Water or ice
101,06.05,Unmapped area,--Unmapped area,Unmapped area
"@

$data = $csv | ConvertFrom-Csv -Delim ','

foreach ($row in $data){

    $line = [System.Collections.ArrayList]@(
        "new Geomaterial {",

        # Replace periods with dashes in HierarchyKey
        "HierarchyKey=`"$($row.HierarchyKey.Replace(".","-"))`",",

        # Escape strings
        "GeoMaterial=`"$($row.GeoMaterial.Replace('`"',"`'"))`",",
        "IndentedName=`"$($row.IndentedName.Replace('`"',"`'"))`",",
        "Definition=`"$($row.Definition.Replace('`"',"`'"))`",",
        "},"
     ) 

     Write-Host $line
}